# Generated by Django 4.2.1 on 2023-05-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_alter_task10_title_alter_task11_title_and_more'),
        ('users', '0002_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorites',
            field=models.ManyToManyField(to='generator.variant'),
        ),
    ]
