# Generated by Django 4.1.7 on 2023-03-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Задание 1', max_length=100)),
                ('content', models.TextField(blank=True, verbose_name='Задание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото к заданию')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл к заданию')),
            ],
            options={
                'verbose_name': 'Задание 1',
                'verbose_name_plural': 'Задание 1',
            },
        ),
    ]
