# Generated by Django 4.1.7 on 2023-03-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Задание 2', max_length=100)),
                ('content', models.TextField(blank=True, verbose_name='Задание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото к заданию')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл к заданию')),
            ],
            options={
                'verbose_name': 'Задание 10',
                'verbose_name_plural': 'Задания 10',
            },
        ),
        migrations.CreateModel(
            name='Task11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Задание 2', max_length=100)),
                ('content', models.TextField(blank=True, verbose_name='Задание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото к заданию')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл к заданию')),
            ],
            options={
                'verbose_name': 'Задание 11',
                'verbose_name_plural': 'Задания 11',
            },
        ),
        migrations.CreateModel(
            name='Task12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Задание 2', max_length=100)),
                ('content', models.TextField(blank=True, verbose_name='Задание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото к заданию')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл к заданию')),
            ],
            options={
                'verbose_name': 'Задание 12',
                'verbose_name_plural': 'Задания 12',
            },
        ),
        migrations.CreateModel(
            name='Task13',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Задание 2', max_length=100)),
                ('content', models.TextField(blank=True, verbose_name='Задание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото к заданию')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл к заданию')),
            ],
            options={
                'verbose_name': 'Задание 13',
                'verbose_name_plural': 'Задания 13',
            },
        ),
        migrations.CreateModel(
            name='Task14',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Задание 2', max_length=100)),
                ('content', models.TextField(blank=True, verbose_name='Задание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото к заданию')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл к заданию')),
            ],
            options={
                'verbose_name': 'Задание 14',
                'verbose_name_plural': 'Задания 14',
            },
        ),
        migrations.CreateModel(
            name='Task15',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Задание 2', max_length=100)),
                ('content', models.TextField(blank=True, verbose_name='Задание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото к заданию')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл к заданию')),
            ],
            options={
                'verbose_name': 'Задание 15',
                'verbose_name_plural': 'Задания 15',
            },
        ),
        migrations.CreateModel(
            name='Task16',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Задание 2', max_length=100)),
                ('content', models.TextField(blank=True, verbose_name='Задание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото к заданию')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл к заданию')),
            ],
            options={
                'verbose_name': 'Задание 16',
                'verbose_name_plural': 'Задания 16',
            },
        ),
        migrations.CreateModel(
            name='Task17',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Задание 2', max_length=100)),
                ('content', models.TextField(blank=True, verbose_name='Задание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото к заданию')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл к заданию')),
            ],
            options={
                'verbose_name': 'Задание 17',
                'verbose_name_plural': 'Задания 17',
            },
        ),
        migrations.CreateModel(
            name='Task18',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Задание 2', max_length=100)),
                ('content', models.TextField(blank=True, verbose_name='Задание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото к заданию')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл к заданию')),
            ],
            options={
                'verbose_name': 'Задание 18',
                'verbose_name_plural': 'Задания 18',
            },
        ),
        migrations.CreateModel(
            name='Task19',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Задание 2', max_length=100)),
                ('content', models.TextField(blank=True, verbose_name='Задание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото к заданию')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл к заданию')),
            ],
            options={
                'verbose_name': 'Задание 19',
                'verbose_name_plural': 'Задания 19',
            },
        ),
        migrations.CreateModel(
            name='Task2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Задание 2', max_length=100)),
                ('content', models.TextField(blank=True, verbose_name='Задание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото к заданию')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл к заданию')),
            ],
            options={
                'verbose_name': 'Задание 2',
                'verbose_name_plural': 'Задание 2',
            },
        ),
        migrations.CreateModel(
            name='Task20',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Задание 2', max_length=100)),
                ('content', models.TextField(blank=True, verbose_name='Задание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото к заданию')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл к заданию')),
            ],
            options={
                'verbose_name': 'Задание 20',
                'verbose_name_plural': 'Задания 20',
            },
        ),
        migrations.CreateModel(
            name='Task21',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Задание 2', max_length=100)),
                ('content', models.TextField(blank=True, verbose_name='Задание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото к заданию')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл к заданию')),
            ],
            options={
                'verbose_name': 'Задание 21',
                'verbose_name_plural': 'Задания 21',
            },
        ),
        migrations.CreateModel(
            name='Task22',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Задание 2', max_length=100)),
                ('content', models.TextField(blank=True, verbose_name='Задание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото к заданию')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл к заданию')),
            ],
            options={
                'verbose_name': 'Задание 22',
                'verbose_name_plural': 'Задания 22',
            },
        ),
        migrations.CreateModel(
            name='Task23',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Задание 2', max_length=100)),
                ('content', models.TextField(blank=True, verbose_name='Задание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото к заданию')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл к заданию')),
            ],
            options={
                'verbose_name': 'Задание 23',
                'verbose_name_plural': 'Задания 23',
            },
        ),
        migrations.CreateModel(
            name='Task24',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Задание 2', max_length=100)),
                ('content', models.TextField(blank=True, verbose_name='Задание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото к заданию')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл к заданию')),
            ],
            options={
                'verbose_name': 'Задание 24',
                'verbose_name_plural': 'Задания 24',
            },
        ),
        migrations.CreateModel(
            name='Task25',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Задание 2', max_length=100)),
                ('content', models.TextField(blank=True, verbose_name='Задание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото к заданию')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл к заданию')),
            ],
            options={
                'verbose_name': 'Задание 25',
                'verbose_name_plural': 'Задания 25',
            },
        ),
        migrations.CreateModel(
            name='Task26',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Задание 2', max_length=100)),
                ('content', models.TextField(blank=True, verbose_name='Задание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото к заданию')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл к заданию')),
            ],
            options={
                'verbose_name': 'Задание 26',
                'verbose_name_plural': 'Задания 26',
            },
        ),
        migrations.CreateModel(
            name='Task27',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Задание 2', max_length=100)),
                ('content', models.TextField(blank=True, verbose_name='Задание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото к заданию')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл к заданию')),
            ],
            options={
                'verbose_name': 'Задание 27',
                'verbose_name_plural': 'Задания 27',
            },
        ),
        migrations.CreateModel(
            name='Task3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Задание 2', max_length=100)),
                ('content', models.TextField(blank=True, verbose_name='Задание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото к заданию')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл к заданию')),
            ],
            options={
                'verbose_name': 'Задание 3',
                'verbose_name_plural': 'Задания 3',
            },
        ),
        migrations.CreateModel(
            name='Task4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Задание 2', max_length=100)),
                ('content', models.TextField(blank=True, verbose_name='Задание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото к заданию')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл к заданию')),
            ],
            options={
                'verbose_name': 'Задание 4',
                'verbose_name_plural': 'Задания 4',
            },
        ),
        migrations.CreateModel(
            name='Task5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Задание 2', max_length=100)),
                ('content', models.TextField(blank=True, verbose_name='Задание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото к заданию')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл к заданию')),
            ],
            options={
                'verbose_name': 'Задание 5',
                'verbose_name_plural': 'Задания 5',
            },
        ),
        migrations.CreateModel(
            name='Task6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Задание 2', max_length=100)),
                ('content', models.TextField(blank=True, verbose_name='Задание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото к заданию')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл к заданию')),
            ],
            options={
                'verbose_name': 'Задание 6',
                'verbose_name_plural': 'Задания 6',
            },
        ),
        migrations.CreateModel(
            name='Task7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Задание 2', max_length=100)),
                ('content', models.TextField(blank=True, verbose_name='Задание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото к заданию')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл к заданию')),
            ],
            options={
                'verbose_name': 'Задание 7',
                'verbose_name_plural': 'Задания 7',
            },
        ),
        migrations.CreateModel(
            name='Task8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Задание 2', max_length=100)),
                ('content', models.TextField(blank=True, verbose_name='Задание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото к заданию')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл к заданию')),
            ],
            options={
                'verbose_name': 'Задание 8',
                'verbose_name_plural': 'Задания 8',
            },
        ),
        migrations.CreateModel(
            name='Task9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Задание 2', max_length=100)),
                ('content', models.TextField(blank=True, verbose_name='Задание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото к заданию')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл к заданию')),
            ],
            options={
                'verbose_name': 'Задание 9',
                'verbose_name_plural': 'Задания 9',
            },
        ),
    ]
