# Generated by Django 4.1.7 on 2023-03-27 12:14

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_task10_task11_task12_task13_task14_task15_task16_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task1',
            name='answer',
            field=models.TextField(verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='task1',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Задание'),
        ),
    ]
