# Generated by Django 4.1.7 on 2023-03-27 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_alter_task1_answer_alter_task1_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('task1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.task1')),
                ('task10', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.task10')),
                ('task11', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.task11')),
                ('task12', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.task12')),
                ('task13', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.task13')),
                ('task14', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.task14')),
                ('task15', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.task15')),
                ('task16', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.task16')),
                ('task17', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.task17')),
                ('task18', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.task18')),
                ('task19', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.task19')),
                ('task2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.task2')),
                ('task20', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.task20')),
                ('task21', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.task21')),
                ('task22', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.task22')),
                ('task23', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.task23')),
                ('task24', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.task24')),
                ('task25', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.task25')),
                ('task26', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.task26')),
                ('task27', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.task27')),
                ('task3', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.task3')),
                ('task4', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.task4')),
                ('task5', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.task5')),
                ('task6', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.task6')),
                ('task7', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.task7')),
                ('task8', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.task8')),
                ('task9', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.task9')),
            ],
            options={
                'verbose_name': 'Вариант',
                'verbose_name_plural': 'Варианты',
            },
        ),
    ]
