# Generated by Django 4.1.7 on 2023-03-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task10',
            name='title',
            field=models.CharField(blank=True, default='Задание 10', max_length=100),
        ),
        migrations.AlterField(
            model_name='task11',
            name='title',
            field=models.CharField(blank=True, default='Задание 11', max_length=100),
        ),
        migrations.AlterField(
            model_name='task12',
            name='title',
            field=models.CharField(blank=True, default='Задание 12', max_length=100),
        ),
        migrations.AlterField(
            model_name='task13',
            name='title',
            field=models.CharField(blank=True, default='Задание 13', max_length=100),
        ),
        migrations.AlterField(
            model_name='task14',
            name='title',
            field=models.CharField(blank=True, default='Задание 14', max_length=100),
        ),
        migrations.AlterField(
            model_name='task15',
            name='title',
            field=models.CharField(blank=True, default='Задание 15', max_length=100),
        ),
        migrations.AlterField(
            model_name='task16',
            name='title',
            field=models.CharField(blank=True, default='Задание 16', max_length=100),
        ),
        migrations.AlterField(
            model_name='task17',
            name='title',
            field=models.CharField(blank=True, default='Задание 17', max_length=100),
        ),
        migrations.AlterField(
            model_name='task18',
            name='title',
            field=models.CharField(blank=True, default='Задание 18', max_length=100),
        ),
        migrations.AlterField(
            model_name='task19',
            name='title',
            field=models.CharField(blank=True, default='Задание 19', max_length=100),
        ),
        migrations.AlterField(
            model_name='task20',
            name='title',
            field=models.CharField(blank=True, default='Задание 20', max_length=100),
        ),
        migrations.AlterField(
            model_name='task21',
            name='title',
            field=models.CharField(blank=True, default='Задание 21', max_length=100),
        ),
        migrations.AlterField(
            model_name='task22',
            name='title',
            field=models.CharField(blank=True, default='Задание 22', max_length=100),
        ),
        migrations.AlterField(
            model_name='task23',
            name='title',
            field=models.CharField(blank=True, default='Задание 23', max_length=100),
        ),
        migrations.AlterField(
            model_name='task24',
            name='title',
            field=models.CharField(blank=True, default='Задание 24', max_length=100),
        ),
        migrations.AlterField(
            model_name='task25',
            name='title',
            field=models.CharField(blank=True, default='Задание 25', max_length=100),
        ),
        migrations.AlterField(
            model_name='task26',
            name='title',
            field=models.CharField(blank=True, default='Задание 26', max_length=100),
        ),
        migrations.AlterField(
            model_name='task27',
            name='title',
            field=models.CharField(blank=True, default='Задание 27', max_length=100),
        ),
        migrations.AlterField(
            model_name='task3',
            name='title',
            field=models.CharField(blank=True, default='Задание 3', max_length=100),
        ),
        migrations.AlterField(
            model_name='task4',
            name='title',
            field=models.CharField(blank=True, default='Задание 4', max_length=100),
        ),
        migrations.AlterField(
            model_name='task5',
            name='title',
            field=models.CharField(blank=True, default='Задание 5', max_length=100),
        ),
        migrations.AlterField(
            model_name='task6',
            name='title',
            field=models.CharField(blank=True, default='Задание 6', max_length=100),
        ),
        migrations.AlterField(
            model_name='task7',
            name='title',
            field=models.CharField(blank=True, default='Задание 7', max_length=100),
        ),
        migrations.AlterField(
            model_name='task8',
            name='title',
            field=models.CharField(blank=True, default='Задание 8', max_length=100),
        ),
        migrations.AlterField(
            model_name='task9',
            name='title',
            field=models.CharField(blank=True, default='Задание 9', max_length=100),
        ),
    ]
